server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 10MB
  data:
    redis:
      host: localhost
      port: 6379

person:
  name: 张三
  age: 11
  birthDay: '2010/10/02 12:12:12'
  like: true
  child:
    name: 李四
    age: 11
    birthDay: '2010/10/02 12:12:12'
    text:
      - abc
      - abc
  dogs:
    - name: 小黑
      age: 11
    - name: 小黄
      age: 12
  cats:
    c1:
      name: 小白
      age: 14
    c2:
      name: 小红
      age: 15
